"""Record human decisions about the data agent accuracy loop.

GENERATED by validation/build_approval_function.py. Edit that and regenerate.

Neither `approved_by` nor `created_by` is a parameter. Both are read from the
caller's Entra token, so a person cannot act as somebody else and a flow
cannot act as a person.

Nothing here applies anything. These functions write rows. A pipeline mirrors
approvals to the eventhouse, and an Activator rule starts the remediation
notebook. If this function could start a notebook, anyone who could call it
could run a job against a governed model.
"""

import uuid
from datetime import datetime, timezone

import fabric.functions as fn

udf = fn.UserDataFunctions()

APPROVED = "approved"
REJECTED = "rejected"

VERDICTS = ("wrong", "misleading", "right")

# Where an instruction takes effect. Agent instructions are applied after the
# query has run, so they change how an answer reads and nothing else.
TARGET_SEMANTIC_MODEL = "semantic_model"
TARGET_DATA_AGENT = "data_agent"


# --------------------------------------------------------------------------
# Shared
# --------------------------------------------------------------------------
#
# Caller-facing parameters are camelCase because Fabric refuses an underscore
# in a user data function parameter name. Column names keep their snake_case,
# because those are the schema's and nothing about the platform touches them.

def _caller(invocation):
    """The verified identity of whoever called this function.

    PreferredUsername is what a person recognises in an audit trail, but it is
    mutable, so the immutable object id is recorded next to it. Neither is
    supplied by the caller: both come from the token the platform validated.
    """
    user = (invocation.executing_user or {}) if invocation else {}
    name = (user.get("PreferredUsername") or "").strip()
    oid = (user.get("Oid") or "").strip()
    if not name and not oid:
        raise fn.UserThrownError(
            "Could not identify you, so nothing was recorded.",
            {"reason": "no executing_user on the invocation context"},
        )
    return name or oid, oid or name


def _cursor(sql_db):
    connection = sql_db.connect()
    return connection, connection.cursor()


def _question(value):
    value = (value or "").strip().upper()
    if not value:
        raise fn.UserThrownError(
            "Pick a question first.", {"reason": "question_id was empty"},
        )
    return value


def _now():
    return datetime.now(timezone.utc)


# --------------------------------------------------------------------------
# The functions
# --------------------------------------------------------------------------

@udf.connection(argName="sqlDb", alias="agentevalsql")
@udf.context(argName="invocation")
@udf.function()
def list_pending_remediations(
    sqlDb: fn.FabricSqlConnection,
    invocation: fn.UserDataFunctionContext,
) -> str:
    """What is waiting for a decision.

    Returns a string rather than a list because a Power BI data function
    button will not bind to a function that returns anything else.
    """
    connection, cursor = _cursor(sqlDb)
    try:
        cursor.execute(
            "SELECT [Question], [Problem], [Target], [Approvable], "
            "       [Add this instruction] "
            "FROM dbo.remediation_queue "
            "WHERE [Status] = 'awaiting approval' "
            "ORDER BY [Question]"
        )
        rows = cursor.fetchall()
    finally:
        cursor.close()
        connection.close()

    if not rows:
        return "Nothing is waiting for a decision."

    lines = []
    for question_id, problem, target, approvable, instruction in rows:
        route = f"approvable, {target}" if approvable else "needs a person"
        lines.append(f"{question_id} ({problem}, {route}): {instruction}")
    return f"{len(rows)} waiting for a decision.\n" + "\n".join(lines)


@udf.connection(argName="sqlDb", alias="agentevalsql")
@udf.context(argName="invocation")
@udf.function()
def approve_remediation(
    sqlDb: fn.FabricSqlConnection,
    invocation: fn.UserDataFunctionContext,
    questionId: str,
    decision: str,
    note: str = "",
) -> str:
    """Record one decision about one proposed sentence.

    Nothing is applied here. This writes the approval row and returns. A
    pipeline mirrors it to the eventhouse within a minute, and the Activator
    rule that watches it starts the remediation notebook.
    """
    question_id = _question(questionId)
    decision = (decision or "").strip().lower()
    if decision not in (APPROVED, REJECTED):
        raise fn.UserThrownError(
            f"Decision must be '{APPROVED}' or '{REJECTED}'.",
            {"received": decision},
        )

    approved_by, oid = _caller(invocation)
    connection, cursor = _cursor(sqlDb)
    try:
        # The latest defect for this question, and whether it is safe to
        # apply. Parameterised, because question_id reaches this from a report
        # input slicer and is caller controlled however much it looks like a
        # dropdown.
        cursor.execute(
            "SELECT TOP 1 d.proposed_instruction, d.instruction_target, "
            "       d.tier, d.auto_appliable "
            "FROM dbo.defects AS d "
            "JOIN dbo.runs AS r ON r.run_id = d.run_id "
            "WHERE d.question_id = ? "
            "ORDER BY r.run_ts DESC",
            question_id,
        )
        defect = cursor.fetchone()
        if defect is None:
            raise fn.UserThrownError(
                f"No open defect for {question_id}.",
                {"hint": "The queue may have moved on. Refresh and look again."},
            )

        instruction, target, tier, auto_appliable = defect

        if decision == APPROVED and not auto_appliable:
            raise fn.UserThrownError(
                f"{question_id} is tier {tier} and has no automatically "
                "appliable fix. It needs a person in the model. Reject it, or "
                "fix it by hand.",
                {"tier": tier},
            )

        if decision == APPROVED and not (instruction or "").strip():
            raise fn.UserThrownError(
                f"{question_id} carries no instruction text to approve.",
                {"hint": "Approving nothing would consume the defect and "
                         "change nothing."},
            )

        if decision == APPROVED:
            cursor.execute(
                "SELECT COUNT(*) FROM dbo.open_approvals WHERE question_id = ?",
                question_id,
            )
            if cursor.fetchone()[0]:
                raise fn.UserThrownError(
                    f"{question_id} already has an approval waiting to be "
                    "applied.",
                    {"hint": "Approving twice would queue the same change again."},
                )

        approval_id = str(uuid.uuid4())
        # The instruction text is copied into the approval rather than
        # referenced. A person approves a specific sentence, and the proposal
        # can change on the next run.
        cursor.execute(
            "INSERT INTO dbo.approvals (approval_id, approved_ts, question_id, "
            "  instruction_target, proposed_instruction, decision, approved_by, "
            "  approver_oid, source, note) "
            "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
            approval_id, _now(), question_id, target, instruction or "",
            decision, approved_by, oid, "report", (note or "").strip(),
        )
        connection.commit()
    finally:
        cursor.close()
        connection.close()

    if decision == REJECTED:
        return f"Rejected {question_id}. Nothing will be applied."

    where = ("the model AI instructions" if target == TARGET_SEMANTIC_MODEL
             else "the data agent instructions")
    return (
        f"Approved {question_id} as {approved_by}. The instruction goes into "
        f"{where}, the remediation runs within about two minutes, and the next "
        f"evaluation says whether it worked. Approval {approval_id}."
    )


@udf.connection(argName="sqlDb", alias="agentevalsql")
@udf.context(argName="invocation")
@udf.function()
def submit_feedback(
    sqlDb: fn.FabricSqlConnection,
    invocation: fn.UserDataFunctionContext,
    questionId: str,
    verdict: str,
    comment: str,
) -> str:
    """Record what a person thinks of an answer.

    This is **not** an approval and cannot become one on its own. It records
    that somebody believes an answer was wrong, which is evidence that a
    defect may exist, and a person triages it later.

    The distinction is the whole point. If a click could turn an opinion into
    a model change, the loop would agree with whoever complained most
    recently, and the score would stop measuring the model.
    """
    question_id = _question(questionId)
    verdict = (verdict or "").strip().lower()
    if verdict not in VERDICTS:
        raise fn.UserThrownError(
            "Verdict must be one of: " + ", ".join(VERDICTS),
            {"received": verdict},
        )
    if not (comment or "").strip():
        raise fn.UserThrownError(
            "Say what was wrong with it.",
            {"reason": "feedback with no comment is not evidence of anything"},
        )

    created_by, oid = _caller(invocation)
    connection, cursor = _cursor(sqlDb)
    try:
        cursor.execute(
            "SELECT COUNT(*) FROM dbo.questions WHERE question_id = ?",
            question_id,
        )
        if not cursor.fetchone()[0]:
            raise fn.UserThrownError(
                f"{question_id} is not in the question bank.",
                {"hint": "Feedback is recorded against a question that is "
                         "actually asked, so it can be joined to its answers."},
            )

        # The most recent run, so the feedback points at the answers it is
        # about rather than floating free of any evidence.
        cursor.execute("SELECT TOP 1 run_id FROM dbo.runs ORDER BY run_ts DESC")
        latest = cursor.fetchone()

        feedback_id = str(uuid.uuid4())
        cursor.execute(
            "INSERT INTO dbo.feedback (feedback_id, created_ts, created_by, "
            "  created_oid, run_id, question_id, verdict, comment, status) "
            "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)",
            feedback_id, _now(), created_by, oid,
            latest[0] if latest else None,
            question_id, verdict, comment.strip(), "new",
        )
        connection.commit()
    finally:
        cursor.close()
        connection.close()

    return (
        f"Thanks. Recorded against {question_id} as {created_by}. This is "
        "evidence for triage, not a change: nothing is applied to the model "
        "until somebody approves a specific sentence."
    )
