"""Record human decisions about the data agent accuracy loop.

GENERATED by validation/build_approval_function.py. Edit that and regenerate.

Neither `approved_by` nor `created_by` is a parameter. Both are read from the
caller's Entra token, so a person cannot act as somebody else and a flow
cannot act as a person.

Nothing here applies anything. These functions write rows. A pipeline mirrors
approvals to the eventhouse, and an Activator rule starts the remediation
notebook. If this function could start a notebook, anyone who could call it
could run a job against a governed model.

The one apparent exception is `approve_similar`, which writes a remediation
row as well as an approval row. It is not applying anything either: the row
records that this decision needs no write of its own, because the sentence is
already being written once by the approval it names.
"""

import uuid
from datetime import datetime, timezone

import fabric.functions as fn

udf = fn.UserDataFunctions()

APPROVED = "approved"
REJECTED = "rejected"

VERDICTS = ("wrong", "misleading", "right")

# The one status string in dbo.remediation_queue that means nobody has
# decided yet. Named here so a comparison against it cannot be spelled two
# ways in two functions.
AWAITING = "awaiting approval"

# Where an instruction takes effect. Agent instructions are applied after the
# query has run, so they change how an answer reads and nothing else.
TARGET_SEMANTIC_MODEL = "semantic_model"
TARGET_DATA_AGENT = "data_agent"


# --------------------------------------------------------------------------
# Shared
# --------------------------------------------------------------------------
#
# Caller-facing parameters are camelCase because Fabric refuses an underscore
# in a user data function parameter name. Column names keep their snake_case,
# because those are the schema's and nothing about the platform touches them.

def _caller(invocation):
    """The verified identity of whoever called this function.

    PreferredUsername is what a person recognises in an audit trail, but it is
    mutable, so the immutable object id is recorded next to it. Neither is
    supplied by the caller: both come from the token the platform validated.
    """
    user = (invocation.executing_user or {}) if invocation else {}
    name = (user.get("PreferredUsername") or "").strip()
    oid = (user.get("Oid") or "").strip()
    if not name and not oid:
        raise fn.UserThrownError(
            "Could not identify you, so nothing was recorded.",
            {"reason": "no executing_user on the invocation context"},
        )
    return name or oid, oid or name


def _cursor(sql_db):
    connection = sql_db.connect()
    return connection, connection.cursor()


def _question(value):
    value = (value or "").strip().upper()
    if not value:
        raise fn.UserThrownError(
            "Pick a question first.", {"reason": "question_id was empty"},
        )
    return value


def _now():
    return datetime.now(timezone.utc)


def _latest_defect(cursor, question_id):
    """The most recent defect for a question, or None.

    Parameterised, because question_id reaches this from a report input
    slicer and is caller controlled however much it looks like a dropdown.
    """
    cursor.execute(
        "SELECT TOP 1 d.proposed_instruction, d.instruction_target, "
        "       d.tier, d.auto_appliable "
        "FROM dbo.defects AS d "
        "JOIN dbo.runs AS r ON r.run_id = d.run_id "
        "WHERE d.question_id = ? "
        "ORDER BY r.run_ts DESC",
        question_id,
    )
    return cursor.fetchone()


def _siblings(cursor, question_id):
    """Other questions whose latest defect proposes the identical sentence.

    The harness proposes from a small library, so one wrong behaviour usually
    appears as the same instruction against several questions at once. They
    are the same decision, and dbo.similar_fixes is where that grouping is
    defined once rather than in each caller.
    """
    cursor.execute(
        "SELECT s.[Question], s.[Status], s.[Target], s.[Add this instruction] "
        "FROM dbo.similar_fixes AS s "
        "JOIN dbo.similar_fixes AS me ON me.[Fix Group] = s.[Fix Group] "
        "WHERE me.[Question] = ? AND s.[Question] <> ? "
        "ORDER BY s.[Question]",
        question_id, question_id,
    )
    return cursor.fetchall()


def _covering_approval(cursor, question_id, decision):
    """The decision this group is being asked to follow, or None.

    The most recent decision of the same kind for this question. Approving a
    group asks for a prior approval; rejecting one asks for a prior rejection.
    Reading either as licence for the other would record agreement nobody
    expressed.
    """
    cursor.execute(
        "SELECT TOP 1 approval_id, proposed_instruction, instruction_target "
        "FROM dbo.approvals "
        "WHERE question_id = ? AND decision = ? "
        "ORDER BY approved_ts DESC",
        question_id, decision,
    )
    return cursor.fetchone()


# --------------------------------------------------------------------------
# The functions
# --------------------------------------------------------------------------

@udf.connection(argName="sqlDb", alias="agentevalsql")
@udf.context(argName="invocation")
@udf.function()
def list_pending_remediations(
    sqlDb: fn.FabricSqlConnection,
    invocation: fn.UserDataFunctionContext,
) -> str:
    """What is waiting for a decision.

    Returns a string rather than a list because a Power BI data function
    button will not bind to a function that returns anything else.
    """
    connection, cursor = _cursor(sqlDb)
    try:
        cursor.execute(
            "SELECT [Question], [Problem], [Target], [Approvable], "
            "       [Add this instruction] "
            "FROM dbo.remediation_queue "
            "WHERE [Status] = 'awaiting approval' "
            "ORDER BY [Question]"
        )
        rows = cursor.fetchall()
    finally:
        cursor.close()
        connection.close()

    if not rows:
        return "Nothing is waiting for a decision."

    lines = []
    for question_id, problem, target, approvable, instruction in rows:
        route = f"approvable, {target}" if approvable else "needs a person"
        lines.append(f"{question_id} ({problem}, {route}): {instruction}")
    return f"{len(rows)} waiting for a decision.\n" + "\n".join(lines)


@udf.connection(argName="sqlDb", alias="agentevalsql")
@udf.context(argName="invocation")
@udf.function()
def approve_remediation(
    sqlDb: fn.FabricSqlConnection,
    invocation: fn.UserDataFunctionContext,
    questionId: str,
    decision: str,
    note: str = "",
) -> str:
    """Record one decision about one proposed sentence.

    Nothing is applied here. This writes the approval row and returns. A
    pipeline mirrors it to the eventhouse within a minute, and the Activator
    rule that watches it starts the remediation notebook.
    """
    question_id = _question(questionId)
    decision = (decision or "").strip().lower()
    if decision not in (APPROVED, REJECTED):
        raise fn.UserThrownError(
            f"Decision must be '{APPROVED}' or '{REJECTED}'.",
            {"received": decision},
        )

    approved_by, oid = _caller(invocation)
    connection, cursor = _cursor(sqlDb)
    try:
        # The latest defect for this question, and whether it is safe to
        # apply.
        defect = _latest_defect(cursor, question_id)
        if defect is None:
            raise fn.UserThrownError(
                f"No open defect for {question_id}.",
                {"hint": "The queue may have moved on. Refresh and look again."},
            )

        instruction, target, tier, auto_appliable = defect

        if decision == APPROVED and not auto_appliable:
            raise fn.UserThrownError(
                f"{question_id} is tier {tier} and has no automatically "
                "appliable fix. It needs a person in the model. Reject it, or "
                "fix it by hand.",
                {"tier": tier},
            )

        if decision == APPROVED and not (instruction or "").strip():
            raise fn.UserThrownError(
                f"{question_id} carries no instruction text to approve.",
                {"hint": "Approving nothing would consume the defect and "
                         "change nothing."},
            )

        if decision == APPROVED:
            cursor.execute(
                "SELECT COUNT(*) FROM dbo.open_approvals WHERE question_id = ?",
                question_id,
            )
            if cursor.fetchone()[0]:
                raise fn.UserThrownError(
                    f"{question_id} already has an approval waiting to be "
                    "applied.",
                    {"hint": "Approving twice would queue the same change again."},
                )

        approval_id = str(uuid.uuid4())
        # The instruction text is copied into the approval rather than
        # referenced. A person approves a specific sentence, and the proposal
        # can change on the next run.
        #
        # covered_by is null: this approval is the one that carries the change.
        cursor.execute(
            "INSERT INTO dbo.approvals (approval_id, approved_ts, question_id, "
            "  instruction_target, proposed_instruction, decision, approved_by, "
            "  approver_oid, source, note, covered_by) "
            "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
            approval_id, _now(), question_id, target, instruction or "",
            decision, approved_by, oid, "report", (note or "").strip(), None,
        )
        connection.commit()

        # Read after the commit, so the count is what the next caller will
        # see rather than what this transaction happens to be holding.
        waiting = [row[0] for row in _siblings(cursor, question_id)
                   if row[1] == AWAITING]
    finally:
        cursor.close()
        connection.close()

    if decision == REJECTED:
        return f"Rejected {question_id}. Nothing will be applied."

    where = ("the model AI instructions" if target == TARGET_SEMANTIC_MODEL
             else "the data agent instructions")
    message = (
        f"Approved {question_id} as {approved_by}. The instruction goes into "
        f"{where}, the remediation runs within about two minutes, and the next "
        f"evaluation says whether it worked. Approval {approval_id}."
    )
    if waiting:
        # Said here, at the moment of approving, because this is when a person
        # can act on it. Finding out later that four other questions carried
        # the same sentence means four more trips through the same queue.
        message += (
            f" {len(waiting)} other question(s) are waiting on this exact "
            f"sentence: {', '.join(waiting)}. They are the same decision. Use "
            "approve_similar to record them together, which marks them "
            "approved without queueing a second copy of a change that is "
            "already being made."
        )
    return message


@udf.connection(argName="sqlDb", alias="agentevalsql")
@udf.context(argName="invocation")
@udf.function()
def list_similar_pending(
    sqlDb: fn.FabricSqlConnection,
    invocation: fn.UserDataFunctionContext,
    questionId: str,
) -> str:
    """Which other questions are waiting on the same sentence.

    Read only. This is what a person looks at before deciding whether to
    approve a group, and it names every question in the group with where it
    has got to, including the ones already decided, because "there are three
    others and two of them are done" is a different situation from "there are
    three others and nobody has looked at them".
    """
    question_id = _question(questionId)
    connection, cursor = _cursor(sqlDb)
    try:
        if _latest_defect(cursor, question_id) is None:
            raise fn.UserThrownError(
                f"No open defect for {question_id}.",
                {"hint": "The queue may have moved on. Refresh and look again."},
            )
        rows = _siblings(cursor, question_id)
    finally:
        cursor.close()
        connection.close()

    if not rows:
        return (
            f"No other question carries the same proposed fix as "
            f"{question_id}. Approving it affects that question alone."
        )

    waiting = [row[0] for row in rows if row[1] == AWAITING]
    lines = [f"{row[0]} ({row[1]})" for row in rows]
    head = (
        f"{len(rows)} other question(s) carry the same proposed fix as "
        f"{question_id}, aimed at {rows[0][2]}:"
    )
    tail = (
        f"\n\n{len(waiting)} of them are still waiting for a decision. "
        "approve_similar records them all at once, without queueing a second "
        "copy of the same change."
        if waiting else
        "\n\nAll of them have already been decided."
    )
    return head + "\n" + "\n".join(lines) + tail


@udf.connection(argName="sqlDb", alias="agentevalsql")
@udf.context(argName="invocation")
@udf.function()
def approve_similar(
    sqlDb: fn.FabricSqlConnection,
    invocation: fn.UserDataFunctionContext,
    questionId: str,
    decision: str,
    note: str = "",
) -> str:
    """Record the same decision for every question carrying the same sentence.

    `questionId` is the question that was decided first. This applies that
    decision to its group and to nothing else.

    An approval recorded here is a real decision by a real person about a real
    question. What it does not do is queue a second copy of a change that is
    already being made: the sentence is one sentence, the model or the agent
    gets one line, and approving it four times would produce four identical
    lines, four remediation runs and four chances for one of them to fail
    halfway.

    So each approved row is written with `covered_by` naming the approval that
    carries the change, together with a remediation row that has no applied
    time. The approval is closed, the loop has nothing to apply, and the
    report can say why.
    """
    question_id = _question(questionId)
    decision = (decision or "").strip().lower()
    if decision not in (APPROVED, REJECTED):
        raise fn.UserThrownError(
            f"Decision must be '{APPROVED}' or '{REJECTED}'.",
            {"received": decision},
        )

    approved_by, oid = _caller(invocation)
    connection, cursor = _cursor(sqlDb)
    try:
        covering = _covering_approval(cursor, question_id, decision)
        if covering is None:
            raise fn.UserThrownError(
                f"{question_id} has not been {decision}, so there is nothing "
                "for the others to follow.",
                {"hint": "Decide one question first. That decision is what "
                         "changes the model or the agent; this records the "
                         "same one for the questions that share its fix."},
            )
        covering_id, instruction, target = covering

        candidates = [row for row in _siblings(cursor, question_id)
                      if row[1] == AWAITING]
        if not candidates:
            return (
                f"Nothing to do. No other question is waiting on the same "
                f"sentence as {question_id}."
            )

        decided = []
        for sibling_id, _status, sibling_target, sibling_instruction in candidates:
            approval_id = str(uuid.uuid4())
            cursor.execute(
                "INSERT INTO dbo.approvals (approval_id, approved_ts, "
                "  question_id, instruction_target, proposed_instruction, "
                "  decision, approved_by, approver_oid, source, note, "
                "  covered_by) "
                "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
                approval_id, _now(), sibling_id, sibling_target,
                sibling_instruction or instruction, decision, approved_by, oid,
                "report", (note or "").strip(),
                covering_id if decision == APPROVED else None,
            )

            if decision == APPROVED:
                # The closing row. persisted, so the approval is not open and
                # no remediation run will pick it up; no applied_ts, because
                # this decision wrote nothing and claiming otherwise would put
                # a change in the history that never happened.
                cursor.execute(
                    "INSERT INTO dbo.remediations (remediation_id, "
                    "  recorded_ts, applied_ts, approval_id, question_id, "
                    "  instruction_target, instruction, approved_by, "
                    "  applied_by, dry_run, persisted, verified, verified_ts, "
                    "  verified_run_id) "
                    "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
                    str(uuid.uuid4()), _now(), None, approval_id, sibling_id,
                    sibling_target, sibling_instruction or instruction,
                    approved_by, f"covered by approval {covering_id}",
                    0, 1, 0, None, None,
                )
            decided.append(sibling_id)

        connection.commit()
    finally:
        cursor.close()
        connection.close()

    if decision == REJECTED:
        return (
            f"Rejected {len(decided)} question(s) carrying the same fix as "
            f"{question_id}: {', '.join(decided)}. Nothing will be applied for "
            "them."
        )

    where = ("the model AI instructions" if target == TARGET_SEMANTIC_MODEL
             else "the data agent instructions")
    return (
        f"Approved {len(decided)} question(s) alongside {question_id}: "
        f"{', '.join(decided)}. The sentence is written to {where} once, by "
        f"the approval for {question_id}. These are recorded as approved and "
        "covered by it, so nothing is queued twice and the next evaluation "
        "run is what says whether the fix worked for all of them."
    )


@udf.connection(argName="sqlDb", alias="agentevalsql")
@udf.context(argName="invocation")
@udf.function()
def submit_feedback(
    sqlDb: fn.FabricSqlConnection,
    invocation: fn.UserDataFunctionContext,
    questionId: str,
    verdict: str,
    comment: str,
) -> str:
    """Record what a person thinks of an answer.

    This is **not** an approval and cannot become one on its own. It records
    that somebody believes an answer was wrong, which is evidence that a
    defect may exist, and a person triages it later.

    The distinction is the whole point. If a click could turn an opinion into
    a model change, the loop would agree with whoever complained most
    recently, and the score would stop measuring the model.
    """
    question_id = _question(questionId)
    verdict = (verdict or "").strip().lower()
    if verdict not in VERDICTS:
        raise fn.UserThrownError(
            "Verdict must be one of: " + ", ".join(VERDICTS),
            {"received": verdict},
        )
    if not (comment or "").strip():
        raise fn.UserThrownError(
            "Say what was wrong with it.",
            {"reason": "feedback with no comment is not evidence of anything"},
        )

    created_by, oid = _caller(invocation)
    connection, cursor = _cursor(sqlDb)
    try:
        cursor.execute(
            "SELECT COUNT(*) FROM dbo.questions WHERE question_id = ?",
            question_id,
        )
        if not cursor.fetchone()[0]:
            raise fn.UserThrownError(
                f"{question_id} is not in the question bank.",
                {"hint": "Feedback is recorded against a question that is "
                         "actually asked, so it can be joined to its answers."},
            )

        # The most recent run, so the feedback points at the answers it is
        # about rather than floating free of any evidence.
        cursor.execute("SELECT TOP 1 run_id FROM dbo.runs ORDER BY run_ts DESC")
        latest = cursor.fetchone()

        feedback_id = str(uuid.uuid4())
        cursor.execute(
            "INSERT INTO dbo.feedback (feedback_id, created_ts, created_by, "
            "  created_oid, run_id, question_id, verdict, comment, status) "
            "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)",
            feedback_id, _now(), created_by, oid,
            latest[0] if latest else None,
            question_id, verdict, comment.strip(), "new",
        )
        connection.commit()
    finally:
        cursor.close()
        connection.close()

    return (
        f"Thanks. Recorded against {question_id} as {created_by}. This is "
        "evidence for triage, not a change: nothing is applied to the model "
        "until somebody approves a specific sentence."
    )
