"""Generate and deploy the approval User Data Function.

This is the button. Three callers, one row:

* **A data function button in a Power BI report.** The person reads the queue,
  types a question id, and clicks Approve. This is the surface that matters,
  because the decision happens next to the evidence.
* **A Power Automate or Logic Apps flow**, behind an Adaptive Card.
* **The REST endpoint**, for anything else.

## Why a function rather than only a flow

A flow builds the approval row from its own expressions, so `approved_by` is
whatever the flow author bound it to. Usually the responder's email, and
nothing enforces that.

`UserDataFunctionContext.executing_user` is read from the caller's Entra token
by the platform, so the identity is verified rather than asserted.
`approved_by` and `created_by` are therefore **not parameters of these
functions**, and cannot be.

## Why SQL rather than the eventhouse

The first version of this file wrote to the eventhouse, which a user data
function cannot reach with a managed connection. It needed a Key Vault generic
connection, a service principal, that principal's secret, and three
environment variables, all to work around one missing connector.

`SQLDB_AgentEval` is a SQL database in Fabric, which **is** a supported
managed connection, so all of that is gone: no vault, no secret, no principal.
The eventhouse still receives approvals, because Activator cannot watch a SQL
database, but that is now a pipeline's job rather than this function's
problem.

Run:
    python validation/build_approval_function.py            # generate only
    python validation/build_approval_function.py --deploy   # and create it
"""

from __future__ import annotations

import argparse
import base64
import json
import subprocess
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from config import (  # noqa: E402
    FABRIC_API,
    SQL_DATABASE_NAME,
    WORKSPACE_ID,
    require,
)

ROOT = Path(__file__).resolve().parent.parent
FUNCTION_DIR = ROOT / "fabric" / "approve_remediation"
ITEM_NAME = "Approve remediation"

# The alias Fabric generates for the managed connection. Set once in the
# portal under Manage connections. It is a connection name rather than an
# identifier, so unlike a workspace id it is safe to commit.
SQL_ALIAS = "agentevalsql"

SCHEMA = (
    "https://developer.microsoft.com/json-schemas/fabric/item/"
    "userDataFunction/definition/1.1.0/schema.json"
)

FUNCTIONS = ("approve_remediation", "submit_feedback", "list_pending_remediations")


# --------------------------------------------------------------------------
# function_app.py
# --------------------------------------------------------------------------

HEADER = '''"""Record human decisions about the data agent accuracy loop.

GENERATED by validation/build_approval_function.py. Edit that and regenerate.

Neither `approved_by` nor `created_by` is a parameter. Both are read from the
caller's Entra token, so a person cannot act as somebody else and a flow
cannot act as a person.

Nothing here applies anything. These functions write rows. A pipeline mirrors
approvals to the eventhouse, and an Activator rule starts the remediation
notebook. If this function could start a notebook, anyone who could call it
could run a job against a governed model.
"""

import uuid
from datetime import datetime, timezone

import fabric.functions as fn

udf = fn.UserDataFunctions()

APPROVED = "approved"
REJECTED = "rejected"

VERDICTS = ("wrong", "misleading", "right")

# Where an instruction takes effect. Agent instructions are applied after the
# query has run, so they change how an answer reads and nothing else.
TARGET_SEMANTIC_MODEL = "semantic_model"
TARGET_DATA_AGENT = "data_agent"

'''

HELPERS = '''
# --------------------------------------------------------------------------
# Shared
# --------------------------------------------------------------------------
#
# Caller-facing parameters are camelCase because Fabric refuses an underscore
# in a user data function parameter name. Column names keep their snake_case,
# because those are the schema's and nothing about the platform touches them.

def _caller(invocation):
    """The verified identity of whoever called this function.

    PreferredUsername is what a person recognises in an audit trail, but it is
    mutable, so the immutable object id is recorded next to it. Neither is
    supplied by the caller: both come from the token the platform validated.
    """
    user = (invocation.executing_user or {}) if invocation else {}
    name = (user.get("PreferredUsername") or "").strip()
    oid = (user.get("Oid") or "").strip()
    if not name and not oid:
        raise fn.UserThrownError(
            "Could not identify you, so nothing was recorded.",
            {"reason": "no executing_user on the invocation context"},
        )
    return name or oid, oid or name


def _cursor(sql_db):
    connection = sql_db.connect()
    return connection, connection.cursor()


def _question(value):
    value = (value or "").strip().upper()
    if not value:
        raise fn.UserThrownError(
            "Pick a question first.", {"reason": "question_id was empty"},
        )
    return value


def _now():
    return datetime.now(timezone.utc)

'''

FUNCTIONS_SOURCE = '''
# --------------------------------------------------------------------------
# The functions
# --------------------------------------------------------------------------

@udf.connection(argName="sqlDb", alias="__SQL_ALIAS__")
@udf.context(argName="invocation")
@udf.function()
def list_pending_remediations(
    sqlDb: fn.FabricSqlConnection,
    invocation: fn.UserDataFunctionContext,
) -> str:
    """What is waiting for a decision.

    Returns a string rather than a list because a Power BI data function
    button will not bind to a function that returns anything else.
    """
    connection, cursor = _cursor(sqlDb)
    try:
        cursor.execute(
            "SELECT [Question], [Problem], [Target], [Approvable], "
            "       [Add this instruction] "
            "FROM dbo.remediation_queue "
            "WHERE [Status] = 'awaiting approval' "
            "ORDER BY [Question]"
        )
        rows = cursor.fetchall()
    finally:
        cursor.close()
        connection.close()

    if not rows:
        return "Nothing is waiting for a decision."

    lines = []
    for question_id, problem, target, approvable, instruction in rows:
        route = f"approvable, {target}" if approvable else "needs a person"
        lines.append(f"{question_id} ({problem}, {route}): {instruction}")
    return f"{len(rows)} waiting for a decision.\\n" + "\\n".join(lines)


@udf.connection(argName="sqlDb", alias="__SQL_ALIAS__")
@udf.context(argName="invocation")
@udf.function()
def approve_remediation(
    sqlDb: fn.FabricSqlConnection,
    invocation: fn.UserDataFunctionContext,
    questionId: str,
    decision: str,
    note: str = "",
) -> str:
    """Record one decision about one proposed sentence.

    Nothing is applied here. This writes the approval row and returns. A
    pipeline mirrors it to the eventhouse within a minute, and the Activator
    rule that watches it starts the remediation notebook.
    """
    question_id = _question(questionId)
    decision = (decision or "").strip().lower()
    if decision not in (APPROVED, REJECTED):
        raise fn.UserThrownError(
            f"Decision must be '{APPROVED}' or '{REJECTED}'.",
            {"received": decision},
        )

    approved_by, oid = _caller(invocation)
    connection, cursor = _cursor(sqlDb)
    try:
        # The latest defect for this question, and whether it is safe to
        # apply. Parameterised, because question_id reaches this from a report
        # input slicer and is caller controlled however much it looks like a
        # dropdown.
        cursor.execute(
            "SELECT TOP 1 d.proposed_instruction, d.instruction_target, "
            "       d.tier, d.auto_appliable "
            "FROM dbo.defects AS d "
            "JOIN dbo.runs AS r ON r.run_id = d.run_id "
            "WHERE d.question_id = ? "
            "ORDER BY r.run_ts DESC",
            question_id,
        )
        defect = cursor.fetchone()
        if defect is None:
            raise fn.UserThrownError(
                f"No open defect for {question_id}.",
                {"hint": "The queue may have moved on. Refresh and look again."},
            )

        instruction, target, tier, auto_appliable = defect

        if decision == APPROVED and not auto_appliable:
            raise fn.UserThrownError(
                f"{question_id} is tier {tier} and has no automatically "
                "appliable fix. It needs a person in the model. Reject it, or "
                "fix it by hand.",
                {"tier": tier},
            )

        if decision == APPROVED and not (instruction or "").strip():
            raise fn.UserThrownError(
                f"{question_id} carries no instruction text to approve.",
                {"hint": "Approving nothing would consume the defect and "
                         "change nothing."},
            )

        if decision == APPROVED:
            cursor.execute(
                "SELECT COUNT(*) FROM dbo.open_approvals WHERE question_id = ?",
                question_id,
            )
            if cursor.fetchone()[0]:
                raise fn.UserThrownError(
                    f"{question_id} already has an approval waiting to be "
                    "applied.",
                    {"hint": "Approving twice would queue the same change again."},
                )

        approval_id = str(uuid.uuid4())
        # The instruction text is copied into the approval rather than
        # referenced. A person approves a specific sentence, and the proposal
        # can change on the next run.
        cursor.execute(
            "INSERT INTO dbo.approvals (approval_id, approved_ts, question_id, "
            "  instruction_target, proposed_instruction, decision, approved_by, "
            "  approver_oid, source, note) "
            "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
            approval_id, _now(), question_id, target, instruction or "",
            decision, approved_by, oid, "report", (note or "").strip(),
        )
        connection.commit()
    finally:
        cursor.close()
        connection.close()

    if decision == REJECTED:
        return f"Rejected {question_id}. Nothing will be applied."

    where = ("the model AI instructions" if target == TARGET_SEMANTIC_MODEL
             else "the data agent instructions")
    return (
        f"Approved {question_id} as {approved_by}. The instruction goes into "
        f"{where}, the remediation runs within about two minutes, and the next "
        f"evaluation says whether it worked. Approval {approval_id}."
    )


@udf.connection(argName="sqlDb", alias="__SQL_ALIAS__")
@udf.context(argName="invocation")
@udf.function()
def submit_feedback(
    sqlDb: fn.FabricSqlConnection,
    invocation: fn.UserDataFunctionContext,
    questionId: str,
    verdict: str,
    comment: str,
) -> str:
    """Record what a person thinks of an answer.

    This is **not** an approval and cannot become one on its own. It records
    that somebody believes an answer was wrong, which is evidence that a
    defect may exist, and a person triages it later.

    The distinction is the whole point. If a click could turn an opinion into
    a model change, the loop would agree with whoever complained most
    recently, and the score would stop measuring the model.
    """
    question_id = _question(questionId)
    verdict = (verdict or "").strip().lower()
    if verdict not in VERDICTS:
        raise fn.UserThrownError(
            "Verdict must be one of: " + ", ".join(VERDICTS),
            {"received": verdict},
        )
    if not (comment or "").strip():
        raise fn.UserThrownError(
            "Say what was wrong with it.",
            {"reason": "feedback with no comment is not evidence of anything"},
        )

    created_by, oid = _caller(invocation)
    connection, cursor = _cursor(sqlDb)
    try:
        cursor.execute(
            "SELECT COUNT(*) FROM dbo.questions WHERE question_id = ?",
            question_id,
        )
        if not cursor.fetchone()[0]:
            raise fn.UserThrownError(
                f"{question_id} is not in the question bank.",
                {"hint": "Feedback is recorded against a question that is "
                         "actually asked, so it can be joined to its answers."},
            )

        # The most recent run, so the feedback points at the answers it is
        # about rather than floating free of any evidence.
        cursor.execute("SELECT TOP 1 run_id FROM dbo.runs ORDER BY run_ts DESC")
        latest = cursor.fetchone()

        feedback_id = str(uuid.uuid4())
        cursor.execute(
            "INSERT INTO dbo.feedback (feedback_id, created_ts, created_by, "
            "  created_oid, run_id, question_id, verdict, comment, status) "
            "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)",
            feedback_id, _now(), created_by, oid,
            latest[0] if latest else None,
            question_id, verdict, comment.strip(), "new",
        )
        connection.commit()
    finally:
        cursor.close()
        connection.close()

    return (
        f"Thanks. Recorded against {question_id} as {created_by}. This is "
        "evidence for triage, not a change: nothing is applied to the model "
        "until somebody approves a specific sentence."
    )
'''


def build_function_app() -> str:
    """The function_app.py source.

    No tenant values are baked in at all now. The SQL alias is a Fabric
    connection name rather than an identifier, so unlike the previous version
    there is nothing here that could point at somebody else's tenant, and no
    difference between the committed copy and the deployed one.
    """
    return HEADER + HELPERS + FUNCTIONS_SOURCE.replace("__SQL_ALIAS__", SQL_ALIAS)


# --------------------------------------------------------------------------
# Item definition
# --------------------------------------------------------------------------

DESCRIPTIONS = {
    "approve_remediation": (
        "Record a human decision about one proposed instruction. The approver "
        "is read from the caller's token, never passed in."
    ),
    "submit_feedback": (
        "Record what a person thinks of an answer. Evidence for triage, never "
        "an approval."
    ),
    "list_pending_remediations": "What is waiting for a decision.",
}

PARAMETERS = {
    "approve_remediation": [
        {"dataType": "str", "name": "questionId"},
        {"dataType": "str", "name": "decision"},
        {"dataType": "str", "name": "note"},
    ],
    "submit_feedback": [
        {"dataType": "str", "name": "questionId"},
        {"dataType": "str", "name": "verdict"},
        {"dataType": "str", "name": "comment"},
    ],
    "list_pending_remediations": [],
}


def build_definition_json() -> dict:
    return {
        "$schema": SCHEMA,
        "runtime": "PYTHON",
        "connectedDataSources": [],
        "functions": [
            {
                "name": name,
                "description": DESCRIPTIONS[name],
                # Off. Every caller goes through Fabric or a connector that
                # already holds an Entra token, and a public endpoint on the
                # function that approves model changes is a bigger surface
                # than the feature is worth.
                "isPublicEndpointEnabled": False,
            }
            for name in FUNCTIONS
        ],
        "libraries": {
            "public": [
                {"name": "fabric-user-data-functions", "type": "PYPI", "version": "1.0"},
            ],
            "private": [],
        },
    }


def build_functions_json() -> dict:
    def entry(name: str) -> dict:
        return {
            "name": name,
            "scriptFile": "function_app.py",
            "bindings": [
                {
                    "methods": ["POST"],
                    "route": "",
                    "authLevel": "Anonymous",
                    "name": "req",
                    "direction": "In",
                    "type": "HttpTrigger",
                },
                {
                    "name": "invocation",
                    "direction": "In",
                    "type": "UserDataFunctionContext",
                },
                {
                    "itemType": None,
                    "subType": "FabricSqlConnection",
                    "alias": SQL_ALIAS,
                    "name": "sqlDb",
                    "direction": "In",
                    "type": "FabricItem",
                },
            ],
            "fabricProperties": {
                "fabricMetadataSchemaVersion": "1.1.0",
                "fabricFunctionParameters": PARAMETERS[name],
                # str, because a Power BI data function button will not bind
                # to a function that returns anything else.
                "fabricFunctionReturnType": "str",
            },
        }

    return {"runtime": "PYTHON", "functionsMetadata": [entry(n) for n in FUNCTIONS]}


def write_files() -> dict[str, str]:
    parts = {
        "function_app.py": build_function_app(),
        "definition.json": json.dumps(build_definition_json(), indent=2) + "\n",
        "resources/functions.json": json.dumps(build_functions_json(), indent=2) + "\n",
    }
    for name, text in parts.items():
        path = FUNCTION_DIR / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    return parts


# --------------------------------------------------------------------------
# Fabric REST
# --------------------------------------------------------------------------

def token() -> str:
    result = subprocess.run(
        ["az", "account", "get-access-token", "--resource", FABRIC_API,
         "--query", "accessToken", "-o", "tsv"],
        capture_output=True, text=True, shell=True, check=True,
    )
    return result.stdout.strip()


def call(method: str, url: str, body: dict | None = None) -> tuple[int, dict, dict]:
    data = json.dumps(body).encode("utf-8") if body is not None else None
    request = urllib.request.Request(
        url, data=data, method=method,
        headers={"Authorization": f"Bearer {token()}",
                 "Content-Type": "application/json"},
    )
    try:
        with urllib.request.urlopen(request, timeout=180) as response:
            raw = response.read().decode("utf-8")
            # A 202 can carry a literal "null" body, which json.loads turns
            # into None rather than a dict, so every caller that reads an id
            # off it would raise AttributeError instead of polling.
            parsed = json.loads(raw) if raw.strip() else {}
            return response.status, (parsed or {}), dict(response.headers)
    except urllib.error.HTTPError as exc:
        raise SystemExit(
            f"HTTP {exc.code} {method} {url}\n"
            + exc.read().decode("utf-8", errors="replace")[:1500]
        ) from None


def wait(operation_id: str) -> None:
    for _ in range(60):
        _, payload, _ = call("GET", f"{FABRIC_API}/v1/operations/{operation_id}")
        status = payload.get("status")
        if status == "Succeeded":
            return
        if status in {"Failed", "Undetermined"}:
            raise SystemExit(f"operation {operation_id} {status}: {payload}")
        time.sleep(5)
    raise SystemExit(f"operation {operation_id} did not finish")


def find_existing() -> str | None:
    _, payload, _ = call(
        "GET", f"{FABRIC_API}/v1/workspaces/{WORKSPACE_ID}/items?type=UserDataFunction"
    )
    for item in payload.get("value", []):
        if item.get("displayName") == ITEM_NAME:
            return item["id"]
    return None


def deploy(parts: dict[str, str]) -> int:
    definition = {
        "parts": [
            {"path": path,
             "payload": base64.b64encode(text.encode("utf-8")).decode("utf-8"),
             "payloadType": "InlineBase64"}
            for path, text in parts.items()
        ]
    }

    existing = find_existing()
    if existing:
        print(f"updating existing function {existing}")
        status, payload, headers = call(
            "POST",
            f"{FABRIC_API}/v1/workspaces/{WORKSPACE_ID}/items/{existing}/updateDefinition",
            {"definition": definition},
        )
        item_id = existing
    else:
        print("creating function")
        status, payload, headers = call(
            "POST", f"{FABRIC_API}/v1/workspaces/{WORKSPACE_ID}/items",
            {"displayName": ITEM_NAME, "type": "UserDataFunction",
             "description": ("Records approvals and feedback for the data agent "
                             "accuracy loop. Identity comes from the caller."),
             "definition": definition},
        )
        item_id = payload.get("id")

    if status == 202:
        operation_id = headers.get("x-ms-operation-id")
        print(f"long running operation {operation_id}")
        wait(operation_id)
        item_id = item_id or find_existing()

    print(f"function ready: {item_id}")
    print()
    print("One thing is not deployable from here. Open the item, choose Manage")
    print(f"connections, add a connection to {SQL_DATABASE_NAME}, and make sure")
    print(f"the generated alias is {SQL_ALIAS!r}. Rename it if it is not.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--deploy", action="store_true",
                        help="create or update the item in Fabric")
    args = parser.parse_args()

    parts = write_files()
    print(f"wrote {len(parts)} part(s) to {FUNCTION_DIR.relative_to(ROOT)}")

    if not args.deploy:
        return 0

    require("FABRIC_WORKSPACE_ID")
    return deploy(parts)


if __name__ == "__main__":
    sys.exit(main())
