"""Generate and deploy the approval User Data Function.

This is the button. Three callers, one row:

* **A data function button in a Power BI report.** The person reads the queue,
  types a question id, and clicks Approve. This is the surface that matters,
  because the decision happens next to the evidence.
* **A Power Automate or Logic Apps flow**, behind an Adaptive Card.
* **The REST endpoint**, for anything else.

## Why a function rather than only a flow

A flow builds the approval row from its own expressions, so `approved_by` is
whatever the flow author bound it to. Usually the responder's email, and
nothing enforces that.

`UserDataFunctionContext.executing_user` is read from the caller's Entra token
by the platform, so the identity is verified rather than asserted.
`approved_by` and `created_by` are therefore **not parameters of these
functions**, and cannot be.

## Why approving a group is one decision and one change

The harness proposes fixes from a small library, so one wrong behaviour
usually appears as the same sentence against four or five questions at once.
Approving them one at a time is five clicks that all mean the same thing, and
four of the five would queue a write that changes nothing because the first
one already added the line.

`approve_similar` records the decision for every question in the group and
marks the extra rows `covered_by` the approval that carries the change, with a
remediation row that has no applied time. Every question has a real decision
against it, and the model or the agent gets the sentence once.

## Why SQL rather than the eventhouse

The first version of this file wrote to the eventhouse, which a user data
function cannot reach with a managed connection. It needed a Key Vault generic
connection, a service principal, that principal's secret, and three
environment variables, all to work around one missing connector.

`SQLDB_AgentEval` is a SQL database in Fabric, which **is** a supported
managed connection, so all of that is gone: no vault, no secret, no principal.
The eventhouse still receives approvals, because Activator cannot watch a SQL
database, but that is now a pipeline's job rather than this function's
problem.

Run:
    python validation/build_approval_function.py            # generate only
    python validation/build_approval_function.py --deploy   # and create it
"""

from __future__ import annotations

import argparse
import base64
import json
import subprocess
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from config import (  # noqa: E402
    FABRIC_API,
    SQL_ALIAS,
    SQL_DATABASE_NAME,
    WORKSPACE_ID,
    require,
)

ROOT = Path(__file__).resolve().parent.parent
FUNCTION_DIR = ROOT / "fabric" / "approve_remediation"
ITEM_NAME = "Approve remediation"

# SQL_ALIAS comes from config, defaulting to "agentevalsql".
#
# It is the alias of the managed connection, which the portal generates from
# the data source's name when somebody adds it. There is no API to create that
# connection or to rename it, so if a tenant generates something else, set
# FABRIC_SQL_ALIAS and redeploy rather than fighting the portal. The default
# is what the committed copy carries, so a plain checkout is unchanged.

SCHEMA = (
    "https://developer.microsoft.com/json-schemas/fabric/item/"
    "userDataFunction/definition/1.1.0/schema.json"
)

FUNCTIONS = ("approve_remediation", "submit_feedback", "list_pending_remediations",
             "list_similar_pending", "approve_similar")


# --------------------------------------------------------------------------
# function_app.py
# --------------------------------------------------------------------------

HEADER = '''"""Record human decisions about the data agent accuracy loop.

GENERATED by validation/build_approval_function.py. Edit that and regenerate.

Neither `approved_by` nor `created_by` is a parameter. Both are read from the
caller's Entra token, so a person cannot act as somebody else and a flow
cannot act as a person.

Nothing here applies anything. These functions write rows. A pipeline mirrors
approvals to the eventhouse, and an Activator rule starts the remediation
notebook. If this function could start a notebook, anyone who could call it
could run a job against a governed model.

The one apparent exception is `approve_similar`, which writes a remediation
row as well as an approval row. It is not applying anything either: the row
records that this decision needs no write of its own, because the sentence is
already being written once by the approval it names.
"""

import uuid
from datetime import datetime, timezone

import fabric.functions as fn

udf = fn.UserDataFunctions()

APPROVED = "approved"
REJECTED = "rejected"

VERDICTS = ("wrong", "misleading", "right")

# The one status string in dbo.remediation_queue that means nobody has
# decided yet. Named here so a comparison against it cannot be spelled two
# ways in two functions.
AWAITING = "awaiting approval"

# Where an instruction takes effect. Agent instructions are applied after the
# query has run, so they change how an answer reads and nothing else.
TARGET_SEMANTIC_MODEL = "semantic_model"
TARGET_DATA_AGENT = "data_agent"

'''

HELPERS = '''
# --------------------------------------------------------------------------
# Shared
# --------------------------------------------------------------------------
#
# Caller-facing parameters are camelCase because Fabric refuses an underscore
# in a user data function parameter name. Column names keep their snake_case,
# because those are the schema's and nothing about the platform touches them.

def _caller(invocation):
    """The verified identity of whoever called this function.

    PreferredUsername is what a person recognises in an audit trail, but it is
    mutable, so the immutable object id is recorded next to it. Neither is
    supplied by the caller: both come from the token the platform validated.
    """
    user = (invocation.executing_user or {}) if invocation else {}
    name = (user.get("PreferredUsername") or "").strip()
    oid = (user.get("Oid") or "").strip()
    if not name and not oid:
        raise fn.UserThrownError(
            "Could not identify you, so nothing was recorded.",
            {"reason": "no executing_user on the invocation context"},
        )
    return name or oid, oid or name


def _cursor(sql_db):
    connection = sql_db.connect()
    return connection, connection.cursor()


def _question(value):
    value = (value or "").strip().upper()
    if not value:
        raise fn.UserThrownError(
            "Pick a question first.", {"reason": "question_id was empty"},
        )
    return value


def _now():
    return datetime.now(timezone.utc)


def _latest_defect(cursor, question_id):
    """The most recent defect for a question, or None.

    Parameterised, because question_id reaches this from a report input
    slicer and is caller controlled however much it looks like a dropdown.
    """
    cursor.execute(
        "SELECT TOP 1 d.proposed_instruction, d.instruction_target, "
        "       d.tier, d.auto_appliable "
        "FROM dbo.defects AS d "
        "JOIN dbo.runs AS r ON r.run_id = d.run_id "
        "WHERE d.question_id = ? "
        "ORDER BY r.run_ts DESC",
        question_id,
    )
    return cursor.fetchone()


def _siblings(cursor, question_id):
    """Other questions whose latest defect proposes the identical sentence.

    The harness proposes from a small library, so one wrong behaviour usually
    appears as the same instruction against several questions at once. They
    are the same decision, and dbo.similar_fixes is where that grouping is
    defined once rather than in each caller.
    """
    cursor.execute(
        "SELECT s.[Question], s.[Status], s.[Target], s.[Add this instruction] "
        "FROM dbo.similar_fixes AS s "
        "JOIN dbo.similar_fixes AS me ON me.[Fix Group] = s.[Fix Group] "
        "WHERE me.[Question] = ? AND s.[Question] <> ? "
        "ORDER BY s.[Question]",
        question_id, question_id,
    )
    return cursor.fetchall()


def _covering_approval(cursor, question_id, decision):
    """The decision this group is being asked to follow, or None.

    The most recent decision of the same kind for this question. Approving a
    group asks for a prior approval; rejecting one asks for a prior rejection.
    Reading either as licence for the other would record agreement nobody
    expressed.
    """
    cursor.execute(
        "SELECT TOP 1 approval_id, proposed_instruction, instruction_target "
        "FROM dbo.approvals "
        "WHERE question_id = ? AND decision = ? "
        "ORDER BY approved_ts DESC",
        question_id, decision,
    )
    return cursor.fetchone()

'''

FUNCTIONS_SOURCE = '''
# --------------------------------------------------------------------------
# The functions
# --------------------------------------------------------------------------

@udf.connection(argName="sqlDb", alias="__SQL_ALIAS__")
@udf.context(argName="invocation")
@udf.function()
def list_pending_remediations(
    sqlDb: fn.FabricSqlConnection,
    invocation: fn.UserDataFunctionContext,
) -> str:
    """What is waiting for a decision.

    Returns a string rather than a list because a Power BI data function
    button will not bind to a function that returns anything else.
    """
    connection, cursor = _cursor(sqlDb)
    try:
        cursor.execute(
            "SELECT [Question], [Problem], [Target], [Approvable], "
            "       [Add this instruction] "
            "FROM dbo.remediation_queue "
            "WHERE [Status] = 'awaiting approval' "
            "ORDER BY [Question]"
        )
        rows = cursor.fetchall()
    finally:
        cursor.close()
        connection.close()

    if not rows:
        return "Nothing is waiting for a decision."

    lines = []
    for question_id, problem, target, approvable, instruction in rows:
        route = f"approvable, {target}" if approvable else "needs a person"
        lines.append(f"{question_id} ({problem}, {route}): {instruction}")
    return f"{len(rows)} waiting for a decision.\\n" + "\\n".join(lines)


@udf.connection(argName="sqlDb", alias="__SQL_ALIAS__")
@udf.context(argName="invocation")
@udf.function()
def approve_remediation(
    sqlDb: fn.FabricSqlConnection,
    invocation: fn.UserDataFunctionContext,
    questionId: str,
    decision: str,
    note: str = "",
) -> str:
    """Record one decision about one proposed sentence.

    Nothing is applied here. This writes the approval row and returns. A
    pipeline mirrors it to the eventhouse within a minute, and the Activator
    rule that watches it starts the remediation notebook.
    """
    question_id = _question(questionId)
    decision = (decision or "").strip().lower()
    if decision not in (APPROVED, REJECTED):
        raise fn.UserThrownError(
            f"Decision must be '{APPROVED}' or '{REJECTED}'.",
            {"received": decision},
        )

    approved_by, oid = _caller(invocation)
    connection, cursor = _cursor(sqlDb)
    try:
        # The latest defect for this question, and whether it is safe to
        # apply.
        defect = _latest_defect(cursor, question_id)
        if defect is None:
            raise fn.UserThrownError(
                f"No open defect for {question_id}.",
                {"hint": "The queue may have moved on. Refresh and look again."},
            )

        instruction, target, tier, auto_appliable = defect

        if decision == APPROVED and not auto_appliable:
            raise fn.UserThrownError(
                f"{question_id} is tier {tier} and has no automatically "
                "appliable fix. It needs a person in the model. Reject it, or "
                "fix it by hand.",
                {"tier": tier},
            )

        if decision == APPROVED and not (instruction or "").strip():
            raise fn.UserThrownError(
                f"{question_id} carries no instruction text to approve.",
                {"hint": "Approving nothing would consume the defect and "
                         "change nothing."},
            )

        if decision == APPROVED:
            cursor.execute(
                "SELECT COUNT(*) FROM dbo.open_approvals WHERE question_id = ?",
                question_id,
            )
            if cursor.fetchone()[0]:
                raise fn.UserThrownError(
                    f"{question_id} already has an approval waiting to be "
                    "applied.",
                    {"hint": "Approving twice would queue the same change again."},
                )

        approval_id = str(uuid.uuid4())
        # The instruction text is copied into the approval rather than
        # referenced. A person approves a specific sentence, and the proposal
        # can change on the next run.
        #
        # covered_by is null: this approval is the one that carries the change.
        cursor.execute(
            "INSERT INTO dbo.approvals (approval_id, approved_ts, question_id, "
            "  instruction_target, proposed_instruction, decision, approved_by, "
            "  approver_oid, source, note, covered_by) "
            "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
            approval_id, _now(), question_id, target, instruction or "",
            decision, approved_by, oid, "report", (note or "").strip(), None,
        )
        connection.commit()

        # Read after the commit, so the count is what the next caller will
        # see rather than what this transaction happens to be holding.
        waiting = [row[0] for row in _siblings(cursor, question_id)
                   if row[1] == AWAITING]
    finally:
        cursor.close()
        connection.close()

    if decision == REJECTED:
        return f"Rejected {question_id}. Nothing will be applied."

    where = ("the model AI instructions" if target == TARGET_SEMANTIC_MODEL
             else "the data agent instructions")
    message = (
        f"Approved {question_id} as {approved_by}. The instruction goes into "
        f"{where}, the remediation runs within about two minutes, and the next "
        f"evaluation says whether it worked. Approval {approval_id}."
    )
    if waiting:
        # Said here, at the moment of approving, because this is when a person
        # can act on it. Finding out later that four other questions carried
        # the same sentence means four more trips through the same queue.
        message += (
            f" {len(waiting)} other question(s) are waiting on this exact "
            f"sentence: {', '.join(waiting)}. They are the same decision. Use "
            "approve_similar to record them together, which marks them "
            "approved without queueing a second copy of a change that is "
            "already being made."
        )
    return message


@udf.connection(argName="sqlDb", alias="__SQL_ALIAS__")
@udf.context(argName="invocation")
@udf.function()
def list_similar_pending(
    sqlDb: fn.FabricSqlConnection,
    invocation: fn.UserDataFunctionContext,
    questionId: str,
) -> str:
    """Which other questions are waiting on the same sentence.

    Read only. This is what a person looks at before deciding whether to
    approve a group, and it names every question in the group with where it
    has got to, including the ones already decided, because "there are three
    others and two of them are done" is a different situation from "there are
    three others and nobody has looked at them".
    """
    question_id = _question(questionId)
    connection, cursor = _cursor(sqlDb)
    try:
        if _latest_defect(cursor, question_id) is None:
            raise fn.UserThrownError(
                f"No open defect for {question_id}.",
                {"hint": "The queue may have moved on. Refresh and look again."},
            )
        rows = _siblings(cursor, question_id)
    finally:
        cursor.close()
        connection.close()

    if not rows:
        return (
            f"No other question carries the same proposed fix as "
            f"{question_id}. Approving it affects that question alone."
        )

    waiting = [row[0] for row in rows if row[1] == AWAITING]
    lines = [f"{row[0]} ({row[1]})" for row in rows]
    head = (
        f"{len(rows)} other question(s) carry the same proposed fix as "
        f"{question_id}, aimed at {rows[0][2]}:"
    )
    tail = (
        f"\\n\\n{len(waiting)} of them are still waiting for a decision. "
        "approve_similar records them all at once, without queueing a second "
        "copy of the same change."
        if waiting else
        "\\n\\nAll of them have already been decided."
    )
    return head + "\\n" + "\\n".join(lines) + tail


@udf.connection(argName="sqlDb", alias="__SQL_ALIAS__")
@udf.context(argName="invocation")
@udf.function()
def approve_similar(
    sqlDb: fn.FabricSqlConnection,
    invocation: fn.UserDataFunctionContext,
    questionId: str,
    decision: str,
    note: str = "",
) -> str:
    """Record the same decision for every question carrying the same sentence.

    `questionId` is the question that was decided first. This applies that
    decision to its group and to nothing else.

    An approval recorded here is a real decision by a real person about a real
    question. What it does not do is queue a second copy of a change that is
    already being made: the sentence is one sentence, the model or the agent
    gets one line, and approving it four times would produce four identical
    lines, four remediation runs and four chances for one of them to fail
    halfway.

    So each approved row is written with `covered_by` naming the approval that
    carries the change, together with a remediation row that has no applied
    time. The approval is closed, the loop has nothing to apply, and the
    report can say why.
    """
    question_id = _question(questionId)
    decision = (decision or "").strip().lower()
    if decision not in (APPROVED, REJECTED):
        raise fn.UserThrownError(
            f"Decision must be '{APPROVED}' or '{REJECTED}'.",
            {"received": decision},
        )

    approved_by, oid = _caller(invocation)
    connection, cursor = _cursor(sqlDb)
    try:
        covering = _covering_approval(cursor, question_id, decision)
        if covering is None:
            raise fn.UserThrownError(
                f"{question_id} has not been {decision}, so there is nothing "
                "for the others to follow.",
                {"hint": "Decide one question first. That decision is what "
                         "changes the model or the agent; this records the "
                         "same one for the questions that share its fix."},
            )
        covering_id, instruction, target = covering

        candidates = [row for row in _siblings(cursor, question_id)
                      if row[1] == AWAITING]
        if not candidates:
            return (
                f"Nothing to do. No other question is waiting on the same "
                f"sentence as {question_id}."
            )

        decided = []
        for sibling_id, _status, sibling_target, sibling_instruction in candidates:
            approval_id = str(uuid.uuid4())
            cursor.execute(
                "INSERT INTO dbo.approvals (approval_id, approved_ts, "
                "  question_id, instruction_target, proposed_instruction, "
                "  decision, approved_by, approver_oid, source, note, "
                "  covered_by) "
                "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
                approval_id, _now(), sibling_id, sibling_target,
                sibling_instruction or instruction, decision, approved_by, oid,
                "report", (note or "").strip(),
                covering_id if decision == APPROVED else None,
            )

            if decision == APPROVED:
                # The closing row. persisted, so the approval is not open and
                # no remediation run will pick it up; no applied_ts, because
                # this decision wrote nothing and claiming otherwise would put
                # a change in the history that never happened.
                cursor.execute(
                    "INSERT INTO dbo.remediations (remediation_id, "
                    "  recorded_ts, applied_ts, approval_id, question_id, "
                    "  instruction_target, instruction, approved_by, "
                    "  applied_by, dry_run, persisted, verified, verified_ts, "
                    "  verified_run_id) "
                    "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
                    str(uuid.uuid4()), _now(), None, approval_id, sibling_id,
                    sibling_target, sibling_instruction or instruction,
                    approved_by, f"covered by approval {covering_id}",
                    0, 1, 0, None, None,
                )
            decided.append(sibling_id)

        connection.commit()
    finally:
        cursor.close()
        connection.close()

    if decision == REJECTED:
        return (
            f"Rejected {len(decided)} question(s) carrying the same fix as "
            f"{question_id}: {', '.join(decided)}. Nothing will be applied for "
            "them."
        )

    where = ("the model AI instructions" if target == TARGET_SEMANTIC_MODEL
             else "the data agent instructions")
    return (
        f"Approved {len(decided)} question(s) alongside {question_id}: "
        f"{', '.join(decided)}. The sentence is written to {where} once, by "
        f"the approval for {question_id}. These are recorded as approved and "
        "covered by it, so nothing is queued twice and the next evaluation "
        "run is what says whether the fix worked for all of them."
    )


@udf.connection(argName="sqlDb", alias="__SQL_ALIAS__")
@udf.context(argName="invocation")
@udf.function()
def submit_feedback(
    sqlDb: fn.FabricSqlConnection,
    invocation: fn.UserDataFunctionContext,
    questionId: str,
    verdict: str,
    comment: str,
) -> str:
    """Record what a person thinks of an answer.

    This is **not** an approval and cannot become one on its own. It records
    that somebody believes an answer was wrong, which is evidence that a
    defect may exist, and a person triages it later.

    The distinction is the whole point. If a click could turn an opinion into
    a model change, the loop would agree with whoever complained most
    recently, and the score would stop measuring the model.
    """
    question_id = _question(questionId)
    verdict = (verdict or "").strip().lower()
    if verdict not in VERDICTS:
        raise fn.UserThrownError(
            "Verdict must be one of: " + ", ".join(VERDICTS),
            {"received": verdict},
        )
    if not (comment or "").strip():
        raise fn.UserThrownError(
            "Say what was wrong with it.",
            {"reason": "feedback with no comment is not evidence of anything"},
        )

    created_by, oid = _caller(invocation)
    connection, cursor = _cursor(sqlDb)
    try:
        cursor.execute(
            "SELECT COUNT(*) FROM dbo.questions WHERE question_id = ?",
            question_id,
        )
        if not cursor.fetchone()[0]:
            raise fn.UserThrownError(
                f"{question_id} is not in the question bank.",
                {"hint": "Feedback is recorded against a question that is "
                         "actually asked, so it can be joined to its answers."},
            )

        # The most recent run, so the feedback points at the answers it is
        # about rather than floating free of any evidence.
        cursor.execute("SELECT TOP 1 run_id FROM dbo.runs ORDER BY run_ts DESC")
        latest = cursor.fetchone()

        feedback_id = str(uuid.uuid4())
        cursor.execute(
            "INSERT INTO dbo.feedback (feedback_id, created_ts, created_by, "
            "  created_oid, run_id, question_id, verdict, comment, status) "
            "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)",
            feedback_id, _now(), created_by, oid,
            latest[0] if latest else None,
            question_id, verdict, comment.strip(), "new",
        )
        connection.commit()
    finally:
        cursor.close()
        connection.close()

    return (
        f"Thanks. Recorded against {question_id} as {created_by}. This is "
        "evidence for triage, not a change: nothing is applied to the model "
        "until somebody approves a specific sentence."
    )
'''


def build_function_app() -> str:
    """The function_app.py source.

    No tenant values are baked in at all now. The SQL alias is a Fabric
    connection name rather than an identifier, so unlike the previous version
    there is nothing here that could point at somebody else's tenant, and no
    difference between the committed copy and the deployed one.
    """
    return HEADER + HELPERS + FUNCTIONS_SOURCE.replace("__SQL_ALIAS__", SQL_ALIAS)


# --------------------------------------------------------------------------
# Item definition
# --------------------------------------------------------------------------

DESCRIPTIONS = {
    "approve_remediation": (
        "Record a human decision about one proposed instruction. The approver "
        "is read from the caller's token, never passed in."
    ),
    "submit_feedback": (
        "Record what a person thinks of an answer. Evidence for triage, never "
        "an approval."
    ),
    "list_pending_remediations": "What is waiting for a decision.",
    "list_similar_pending": (
        "Which other questions are waiting on the same proposed sentence as "
        "this one. Read only."
    ),
    "approve_similar": (
        "Record the same decision for every question carrying the same "
        "proposed sentence. Approved rows are marked as covered by the "
        "approval that carries the change, so nothing is applied twice."
    ),
}

PARAMETERS = {
    "approve_remediation": [
        {"dataType": "str", "name": "questionId"},
        {"dataType": "str", "name": "decision"},
        {"dataType": "str", "name": "note"},
    ],
    "submit_feedback": [
        {"dataType": "str", "name": "questionId"},
        {"dataType": "str", "name": "verdict"},
        {"dataType": "str", "name": "comment"},
    ],
    "list_pending_remediations": [],
    "list_similar_pending": [
        {"dataType": "str", "name": "questionId"},
    ],
    "approve_similar": [
        {"dataType": "str", "name": "questionId"},
        {"dataType": "str", "name": "decision"},
        {"dataType": "str", "name": "note"},
    ],
}


def build_definition_json() -> dict:
    return {
        "$schema": SCHEMA,
        "runtime": "PYTHON",
        "connectedDataSources": [],
        "functions": [
            {
                "name": name,
                "description": DESCRIPTIONS[name],
                # Off. Every caller goes through Fabric or a connector that
                # already holds an Entra token, and a public endpoint on the
                # function that approves model changes is a bigger surface
                # than the feature is worth.
                "isPublicEndpointEnabled": False,
            }
            for name in FUNCTIONS
        ],
        "libraries": {
            "public": [
                {"name": "fabric-user-data-functions", "type": "PYPI", "version": "1.0"},
            ],
            "private": [],
        },
    }


def build_functions_json() -> dict:
    def entry(name: str) -> dict:
        return {
            "name": name,
            "scriptFile": "function_app.py",
            "bindings": [
                {
                    "methods": ["POST"],
                    "route": "",
                    "authLevel": "Anonymous",
                    "name": "req",
                    "direction": "In",
                    "type": "HttpTrigger",
                },
                {
                    "name": "invocation",
                    "direction": "In",
                    "type": "UserDataFunctionContext",
                },
                {
                    "itemType": None,
                    "subType": "FabricSqlConnection",
                    "alias": SQL_ALIAS,
                    "name": "sqlDb",
                    "direction": "In",
                    "type": "FabricItem",
                },
            ],
            "fabricProperties": {
                "fabricMetadataSchemaVersion": "1.1.0",
                "fabricFunctionParameters": PARAMETERS[name],
                # str, because a Power BI data function button will not bind
                # to a function that returns anything else.
                "fabricFunctionReturnType": "str",
            },
        }

    return {"runtime": "PYTHON", "functionsMetadata": [entry(n) for n in FUNCTIONS]}


def write_files() -> dict[str, str]:
    parts = {
        "function_app.py": build_function_app(),
        "definition.json": json.dumps(build_definition_json(), indent=2) + "\n",
        "resources/functions.json": json.dumps(build_functions_json(), indent=2) + "\n",
    }
    for name, text in parts.items():
        path = FUNCTION_DIR / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    return parts


# --------------------------------------------------------------------------
# Fabric REST
# --------------------------------------------------------------------------

def token() -> str:
    result = subprocess.run(
        ["az", "account", "get-access-token", "--resource", FABRIC_API,
         "--query", "accessToken", "-o", "tsv"],
        capture_output=True, text=True, shell=True, check=True,
    )
    return result.stdout.strip()


def call(method: str, url: str, body: dict | None = None) -> tuple[int, dict, dict]:
    data = json.dumps(body).encode("utf-8") if body is not None else None
    request = urllib.request.Request(
        url, data=data, method=method,
        headers={"Authorization": f"Bearer {token()}",
                 "Content-Type": "application/json"},
    )
    try:
        with urllib.request.urlopen(request, timeout=180) as response:
            raw = response.read().decode("utf-8")
            # A 202 can carry a literal "null" body, which json.loads turns
            # into None rather than a dict, so every caller that reads an id
            # off it would raise AttributeError instead of polling.
            parsed = json.loads(raw) if raw.strip() else {}
            return response.status, (parsed or {}), dict(response.headers)
    except urllib.error.HTTPError as exc:
        raise SystemExit(
            f"HTTP {exc.code} {method} {url}\n"
            + exc.read().decode("utf-8", errors="replace")[:1500]
        ) from None


class DeployFailed(Exception):
    """The platform rejected the update.

    Separate from a bad request, because it is worth retrying once. The
    update is atomic: an item observed straight after one of these failures
    still had its previous definition, connection included, so a retry cannot
    land a half-applied change.
    """


def wait(operation_id: str) -> None:
    for _ in range(60):
        _, payload, _ = call("GET", f"{FABRIC_API}/v1/operations/{operation_id}")
        status = payload.get("status")
        if status == "Succeeded":
            return
        if status in {"Failed", "Undetermined"}:
            raise DeployFailed(f"operation {operation_id} {status}: {payload}")
        time.sleep(5)
    raise DeployFailed(f"operation {operation_id} did not finish")


def find_existing() -> str | None:
    _, payload, _ = call(
        "GET", f"{FABRIC_API}/v1/workspaces/{WORKSPACE_ID}/items?type=UserDataFunction"
    )
    for item in payload.get("value", []):
        if item.get("displayName") == ITEM_NAME:
            return item["id"]
    return None


class CouldNotRead(Exception):
    """The deployed definition could not be read.

    Its own exception because the caller must not treat it as "there was
    nothing to carry over". Those two look identical and mean opposite
    things: one is a first deploy, the other is about to delete a connection.
    """


def deployed_definition(item_id: str) -> dict:
    """The item definition currently in the workspace, as a parts dict.

    Raises `CouldNotRead` rather than returning empty when the read fails.
    An empty dict means "this item has no definition parts", and a caller
    that cannot tell that apart from "the API did not answer" will happily
    deploy a definition with no connections and delete a working one.
    """
    status, payload, headers = call(
        "POST",
        f"{FABRIC_API}/v1/workspaces/{WORKSPACE_ID}/items/{item_id}/getDefinition",
    )
    if status == 202:
        location = headers.get("Location", "")
        if not location:
            raise CouldNotRead("the long running getDefinition returned no Location")
        for _ in range(60):
            time.sleep(3)
            _, body, head = call("GET", location)
            state = body.get("status")
            if state == "Succeeded":
                result = head.get("Location")
                if result:
                    _, payload, _ = call("GET", result)
                break
            if state in {"Failed", "Undetermined"}:
                raise CouldNotRead(f"getDefinition {state}")
        else:
            raise CouldNotRead("getDefinition did not finish")
    elif status not in (200, 201):
        raise CouldNotRead(f"getDefinition returned {status}")

    parts = {}
    for part in (payload or {}).get("definition", {}).get("parts", []):
        try:
            parts[part["path"]] = base64.b64decode(part["payload"]).decode("utf-8")
        except Exception as exc:  # noqa: BLE001
            raise CouldNotRead(f"a definition part would not decode: {exc}") from None
    if not parts:
        raise CouldNotRead("getDefinition returned no parts")
    return parts


def carry_over_connections(parts: dict[str, str], deployed: dict[str, str]) -> None:
    """Keep the managed connection somebody added in the portal.

    `connectedDataSources` carries a `dmtsConnectionId`, which is a tenant
    object created when a person picks the database under Manage connections.
    It cannot be generated here, so this file builds the definition with an
    empty list.

    An empty list is not "leave it alone". `updateDefinition` replaces the
    whole definition, so deploying without this **deletes the connection**,
    and every function that takes `sqlDb` then fails with "Unable to load data
    successfully for fabric item". The report says a decision could not be
    recorded, and nothing anywhere says why.

    That happened. The deploy printed its usual reminder to go and add the
    connection, which reads like setup advice on a first run and like noise on
    every run after, so it was the least likely line to be believed.

    This is the same guard as `carry_over_button_action` in the report
    builder, for the same reason: a deploy must not silently destroy the one
    part of the item a person had to configure by hand.
    """
    if "definition.json" not in deployed:
        return
    try:
        current = json.loads(deployed["definition.json"])
    except json.JSONDecodeError:
        return

    sources = current.get("connectedDataSources") or []
    if not sources:
        return

    fresh = json.loads(parts["definition.json"])
    fresh["connectedDataSources"] = sources
    parts["definition.json"] = json.dumps(fresh, indent=2) + "\n"

    aliases = [s.get("alias") for s in sources if s.get("alias")]
    print(f"kept the existing managed connection(s) ({', '.join(aliases)})")

    # An alias the code does not use is a connection nobody will reach, and
    # the failure looks identical to having no connection at all.
    if SQL_ALIAS not in aliases:
        print()
        print(f"WARNING: this item's connection alias is {aliases[0]!r}, but "
              f"every function asks for {SQL_ALIAS!r}.")
        print("They will fail with 'Unable to load data successfully for "
              "fabric item' until those match.")
        print("Fix it whichever way is easier:")
        print(f"  $env:FABRIC_SQL_ALIAS = '{aliases[0]}'   # then re-run --deploy")
        print(f"  or rename the alias to {SQL_ALIAS!r} under Manage connections")


def deploy(parts: dict[str, str]) -> int:
    existing = find_existing()

    if existing:
        # Fail closed. Deploying without reading the deployed copy first would
        # replace the definition with one that has no connections, which is
        # how this script once deleted a working one. Refusing is recoverable;
        # a silent wipe is a broken report and no explanation.
        try:
            carry_over_connections(parts, deployed_definition(existing))
        except CouldNotRead as exc:
            raise SystemExit(
                f"could not read the deployed item: {exc}\n\n"
                "Nothing was deployed. updateDefinition replaces the whole "
                "definition, so deploying without first reading what is there "
                "would delete the managed connection and break every "
                "approval. Try again, and if it keeps failing, check that you "
                "can open the item in the portal."
            ) from None

    definition = {
        "parts": [
            {"path": path,
             "payload": base64.b64encode(text.encode("utf-8")).decode("utf-8"),
             "payloadType": "InlineBase64"}
            for path, text in parts.items()
        ]
    }

    def push() -> tuple[int, dict, dict, str]:
        if existing:
            print(f"updating existing function {existing}")
            status, payload, headers = call(
                "POST",
                f"{FABRIC_API}/v1/workspaces/{WORKSPACE_ID}/items/{existing}/updateDefinition",
                {"definition": definition},
            )
            return status, payload, headers, existing
        print("creating function")
        status, payload, headers = call(
            "POST", f"{FABRIC_API}/v1/workspaces/{WORKSPACE_ID}/items",
            {"displayName": ITEM_NAME, "type": "UserDataFunction",
             "description": ("Records approvals and feedback for the data agent "
                             "accuracy loop. Identity comes from the caller."),
             "definition": definition},
        )
        return status, payload, headers, payload.get("id")

    # Retried once, because the platform's own function deployment step fails
    # intermittently with a bare "Azure function deployment failed with
    # error:" and succeeds on the next attempt. The update is atomic, so the
    # retry starts from the same place: an item inspected straight after one
    # of these failures still had its previous definition, connection
    # included.
    for attempt in (1, 2):
        status, payload, headers, item_id = push()
        if status != 202:
            break
        operation_id = headers.get("x-ms-operation-id")
        print(f"long running operation {operation_id}")
        try:
            wait(operation_id)
            item_id = item_id or find_existing()
            break
        except DeployFailed as exc:
            if attempt == 2:
                raise SystemExit(
                    f"{exc}\n\nTwice. Nothing was changed: this update is "
                    "atomic, so the item still has the definition it had "
                    "before. Try again later, or look at the item in the "
                    "portal."
                ) from None
            print(f"  {exc}")
            print("  that step fails intermittently. Nothing was changed, "
                  "retrying once.")
            time.sleep(10)

    print(f"function ready: {item_id}")

    kept = json.loads(parts["definition.json"]).get("connectedDataSources") or []
    if not kept:
        print()
        print("This item has NO managed connection, so every function that")
        print("takes sqlDb will fail with 'Unable to load data successfully")
        print("for fabric item' until it does.")
        print()
        print(f"  1. Open {ITEM_NAME!r} in the workspace")
        print("  2. Manage connections > Add data connection")
        print(f"  3. Pick {SQL_DATABASE_NAME}, then Connect")
        print(f"  4. Check the generated alias. This code asks for {SQL_ALIAS!r}.")
        print("     If it differs, either rename it there, or set")
        print("     FABRIC_SQL_ALIAS to the generated one and re-run --deploy.")
        print()
        print("There is no API for this. The connection is minted by that")
        print("portal flow and nothing else can create it.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--deploy", action="store_true",
                        help="create or update the item in Fabric")
    args = parser.parse_args()

    parts = write_files()
    print(f"wrote {len(parts)} part(s) to {FUNCTION_DIR.relative_to(ROOT)}")

    if not args.deploy:
        return 0

    require("FABRIC_WORKSPACE_ID")
    return deploy(parts)


if __name__ == "__main__":
    sys.exit(main())
