"""Publish the question bank from git into the SQL database.

Git authors, SQL publishes. That split is deliberate and it is the answer to
"why not just keep the questions in a table".

The bank is the measuring instrument. The first rule in this repo is *ask the
questions exactly as written; a reworded question is a hidden failure*, and
`question-bank.md` is in version control so that rewording one is a diff
somebody reviews. In a mutable table, a question can be softened by anyone
with write access, the score rises, and nothing anywhere records that the
instrument changed. That is the one failure the whole loop exists to catch,
and it would be self-inflicted.

So the markdown stays the source of truth, and this publishes it, stamping
every row with `bank_sha`. Every run records the hash it ran against, which
means two runs measured with different instruments are visibly not
comparable rather than quietly plotted on the same line.

Run:
    python validation/publish_question_bank.py            # print the SQL
    python validation/publish_question_bank.py --sha      # just the hash
"""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

BANK_PATH = Path(__file__).resolve().parent / "question-bank.md"

SCORED = "scored"
PROBE = "probe"

# Q01 to Q15 are the score. F01 to F03 are guardrail probes that sit outside
# it, because for those a refusal can be the correct behaviour.
ROW = re.compile(r"^\|\s*(Q\d{2}|F\d{2})\s*\|(.+?)\|(.+?)\|\s*$")


def bank_text() -> str:
    return BANK_PATH.read_text(encoding="utf-8")


def bank_sha(text: str | None = None) -> str:
    """The identity of the instrument.

    Hashes the parsed questions rather than the file, so that editing prose
    around the tables does not invalidate a run, while changing a single
    character of a question does.
    """
    questions = parse(text if text is not None else bank_text())
    payload = "\n".join(
        f"{q['question_id']}|{q['kind']}|{q['prompt']}" for q in questions
    )
    return hashlib.sha1(payload.encode("utf-8")).hexdigest()  # noqa: S324


def parse(text: str | None = None) -> list[dict]:
    """Every question in the bank, in the order it must be asked."""
    text = text if text is not None else bank_text()
    questions: list[dict] = []
    seen: set[str] = set()

    for line in text.splitlines():
        match = ROW.match(line.strip())
        if not match:
            continue
        question_id, prompt, third = (part.strip() for part in match.groups())
        if question_id in seen:
            # The bank lists probes twice, once in a summary and once with
            # their good outcome. First occurrence wins.
            continue
        seen.add(question_id)

        kind = PROBE if question_id.startswith("F") else SCORED
        questions.append({
            "question_id": question_id,
            "kind": kind,
            "ordinal": len(questions) + 1,
            "prompt": prompt,
            "tests": third if kind == SCORED else None,
            "good_outcome": third if kind == PROBE else None,
        })

    if not questions:
        raise SystemExit(
            f"parsed no questions from {BANK_PATH.name}. The table format "
            "changed, and publishing an empty bank would silently orphan "
            "every run."
        )
    return questions


def quote(value: str | None) -> str:
    if value is None:
        return "NULL"
    return "N'" + value.replace("'", "''") + "'"


def build_merge(questions: list[dict] | None = None, sha: str | None = None) -> str:
    """An idempotent publish.

    MERGE rather than DELETE and INSERT, because `answers` and `defects` carry
    foreign keys to `questions`. Deleting a question to republish it would
    take every historical answer with it, or fail, and either way the history
    is what makes a trend line mean anything.
    """
    questions = questions if questions is not None else parse()
    sha = sha or bank_sha()

    values = ",\n".join(
        "    ({qid}, {kind}, {ordinal}, {prompt}, {tests}, {outcome})".format(
            qid=quote(q["question_id"]), kind=quote(q["kind"]),
            ordinal=q["ordinal"], prompt=quote(q["prompt"]),
            tests=quote(q["tests"]), outcome=quote(q["good_outcome"]),
        )
        for q in questions
    )

    return f"""-- GENERATED by validation/publish_question_bank.py. Do not edit.
--
-- Published from validation/question-bank.md at bank_sha {sha}.
-- The markdown is the source of truth. Editing dbo.questions directly is
-- overwritten by the next publish.

MERGE dbo.questions AS target
USING (VALUES
{values}
) AS source (question_id, kind, ordinal, prompt, tests, good_outcome)
ON target.question_id = source.question_id
WHEN MATCHED THEN UPDATE SET
    kind         = source.kind,
    ordinal      = source.ordinal,
    prompt       = source.prompt,
    tests        = source.tests,
    good_outcome = source.good_outcome,
    bank_sha     = '{sha}',
    published_ts = SYSUTCDATETIME()
WHEN NOT MATCHED BY TARGET THEN
    INSERT (question_id, kind, ordinal, prompt, tests, good_outcome,
            bank_sha, published_ts)
    VALUES (source.question_id, source.kind, source.ordinal, source.prompt,
            source.tests, source.good_outcome, '{sha}', SYSUTCDATETIME());

-- Deliberately no WHEN NOT MATCHED BY SOURCE THEN DELETE. A question removed
-- from the bank keeps its history; it simply stops being asked. Deleting it
-- would cascade into every answer ever recorded for it.
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--sha", action="store_true",
                        help="print the bank hash and exit")
    parser.add_argument("--list", action="store_true",
                        help="print the parsed questions")
    args = parser.parse_args()

    questions = parse()
    sha = bank_sha()

    if args.sha:
        print(sha)
        return 0

    if args.list:
        for q in questions:
            print(f"{q['question_id']}  {q['kind']:6}  {q['prompt']}")
        print(f"\n{len(questions)} question(s), bank_sha {sha}")
        return 0

    print(build_merge(questions, sha))
    return 0


if __name__ == "__main__":
    sys.exit(main())
