-- GENERATED by validation/build_sql_schema.py. Do not edit.
--
-- Every statement is guarded, so this is safe to run repeatedly and
-- safe to resume after a partial failure.

IF OBJECT_ID('dbo.questions', 'U') IS NULL
BEGIN
    -- Published from validation/question-bank.md. Never authored here.
    --
    -- The bank is the measuring instrument. If it were editable at runtime,
    -- somebody could soften a question, the score would rise, and nothing would
    -- record that the instrument had changed. bank_sha is what makes that
    -- visible: two runs with different hashes are not comparable.
    CREATE TABLE dbo.questions (
        question_id   varchar(8)     NOT NULL PRIMARY KEY,
        kind          varchar(16)    NOT NULL,   -- 'scored' | 'probe'
        ordinal       int            NOT NULL,
        prompt        nvarchar(1000) NOT NULL,
        tests         nvarchar(1000) NULL,
        good_outcome  nvarchar(1000) NULL,       -- probes only
        bank_sha      char(40)       NOT NULL,
        published_ts  datetime2(3)   NOT NULL
    );
END;
GO

IF OBJECT_ID('dbo.runs', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.runs (
        run_id                uniqueidentifier NOT NULL PRIMARY KEY,
        run_ts                datetime2(3)     NOT NULL,
        surface               varchar(64)      NOT NULL,
        bank_sha              char(40)         NOT NULL,
        score                 int              NOT NULL,
        max_score             int              NOT NULL,
        previous_score        int              NULL,
        flake_count           int              NOT NULL,
        failure_count         int              NOT NULL,
        guardrails_lost_count int              NOT NULL,
        errored_count         int              NOT NULL,
        alert_severity        varchar(16)      NOT NULL,
        alert_detail          nvarchar(max)    NULL
    );
END;
GO

IF OBJECT_ID('dbo.answers', 'U') IS NULL
BEGIN
    -- One row per attempt, not per question. The repeats are the point: a
    -- question answered correctly twice out of three is the finding.
    CREATE TABLE dbo.answers (
        run_id         uniqueidentifier NOT NULL,
        question_id    varchar(8)       NOT NULL,
        attempt        int              NOT NULL,
        grade          varchar(16)      NOT NULL,
        classification varchar(24)      NOT NULL,
        detail         nvarchar(max)    NULL,
        latency_ms     int              NOT NULL,
        answer         nvarchar(max)    NULL,
        CONSTRAINT pk_answers PRIMARY KEY (run_id, question_id, attempt),
        CONSTRAINT fk_answers_run
            FOREIGN KEY (run_id) REFERENCES dbo.runs(run_id),
        CONSTRAINT fk_answers_question
            FOREIGN KEY (question_id) REFERENCES dbo.questions(question_id)
    );
END;
GO

IF OBJECT_ID('dbo.defects', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.defects (
        run_id               uniqueidentifier NOT NULL,
        question_id          varchar(8)       NOT NULL,
        classification       varchar(32)      NOT NULL,
        tier                 int              NOT NULL,
        fix_target           nvarchar(200)    NOT NULL,
        instruction_target   varchar(32)      NOT NULL,  -- 'semantic_model' | 'data_agent' | ''
        proposed_instruction nvarchar(max)    NULL,
        rationale            nvarchar(max)    NOT NULL,
        auto_appliable       bit              NOT NULL,
        CONSTRAINT pk_defects PRIMARY KEY (run_id, question_id),
        CONSTRAINT fk_defects_run
            FOREIGN KEY (run_id) REFERENCES dbo.runs(run_id),
        CONSTRAINT fk_defects_question
            FOREIGN KEY (question_id) REFERENCES dbo.questions(question_id)
    );
END;
GO

IF OBJECT_ID('dbo.feedback', 'U') IS NULL
BEGIN
    -- A person saying an answer was wrong. This is NOT an approval and can never
    -- become one on its own.
    --
    -- Feedback is evidence that a defect may exist. If a click could turn an
    -- opinion into a model change, the loop would agree with whoever complained
    -- most recently, and the score would stop measuring the model.
    --
    -- created_by is the logged-in report user, read from their token by the
    -- function. It is not a parameter, so it cannot be someone else's name.
    CREATE TABLE dbo.feedback (
        feedback_id  uniqueidentifier NOT NULL PRIMARY KEY,
        created_ts   datetime2(3)     NOT NULL,
        created_by   nvarchar(256)    NOT NULL,
        created_oid  varchar(64)      NOT NULL,
        run_id       uniqueidentifier NULL,
        question_id  varchar(8)       NOT NULL,
        verdict      varchar(16)      NOT NULL,  -- 'wrong' | 'misleading' | 'right'
        comment      nvarchar(max)    NOT NULL,
        status       varchar(24)      NOT NULL,  -- 'new' | 'triaged' | 'dismissed'
        CONSTRAINT fk_feedback_question
            FOREIGN KEY (question_id) REFERENCES dbo.questions(question_id)
    );
END;
GO

IF OBJECT_ID('dbo.approvals', 'U') IS NULL
BEGIN
    -- One human decision about one sentence.
    --
    -- proposed_instruction is a copy of the text that was approved, not a
    -- reference to the defect that proposed it. The proposal can change on the
    -- next run; what was agreed cannot.
    CREATE TABLE dbo.approvals (
        approval_id          uniqueidentifier NOT NULL PRIMARY KEY,
        approved_ts          datetime2(3)     NOT NULL,
        question_id          varchar(8)       NOT NULL,
        instruction_target   varchar(32)      NOT NULL,
        proposed_instruction nvarchar(max)    NOT NULL,
        decision             varchar(16)      NOT NULL,
        approved_by          nvarchar(256)    NOT NULL,
        approver_oid         varchar(64)      NOT NULL,
        source               varchar(16)      NOT NULL,  -- 'report' | 'card' | 'cli'
        note                 nvarchar(max)    NULL,
        -- Stamped by the mirror pipeline. An approval with a null mirrored_ts and
        -- an old approved_ts never reached the eventhouse, so the rule never
        -- fired. That is a query, rather than a mystery.
        mirrored_ts          datetime2(3)     NULL,
        CONSTRAINT fk_approvals_question
            FOREIGN KEY (question_id) REFERENCES dbo.questions(question_id)
    );
END;
GO

IF OBJECT_ID('dbo.remediations', 'U') IS NULL
BEGIN
    -- Mirrored back from the eventhouse by the pipeline, because the remediation
    -- notebook still writes there. Kept here so open_approvals can be a view and
    -- the report can show status without crossing stores.
    CREATE TABLE dbo.remediations (
        remediation_id     uniqueidentifier NOT NULL PRIMARY KEY,
        recorded_ts        datetime2(3)     NOT NULL,
        applied_ts         datetime2(3)     NULL,
        approval_id        uniqueidentifier NOT NULL,
        question_id        varchar(8)       NOT NULL,
        instruction_target varchar(32)      NOT NULL,
        instruction        nvarchar(max)    NOT NULL,
        approved_by        nvarchar(256)    NOT NULL,
        applied_by         nvarchar(256)    NOT NULL,
        dry_run            bit              NOT NULL,
        persisted          bit              NOT NULL,
        verified           bit              NOT NULL,
        verified_ts        datetime2(3)     NULL,
        verified_run_id    uniqueidentifier NULL
    );
END;
GO

IF OBJECT_ID('dbo.open_approvals', 'V') IS NOT NULL
    DROP VIEW dbo.open_approvals;
GO
CREATE VIEW dbo.open_approvals AS
SELECT a.*
FROM dbo.approvals AS a
WHERE a.decision = 'approved'
  AND NOT EXISTS (
      SELECT 1 FROM dbo.remediations AS r
      WHERE r.approval_id = a.approval_id AND r.persisted = 1
  );
GO

-- What a person reads before deciding. One row per question, its latest
-- defect, and where that question has got to.
IF OBJECT_ID('dbo.remediation_queue', 'V') IS NOT NULL
    DROP VIEW dbo.remediation_queue;
GO
CREATE VIEW dbo.remediation_queue AS
WITH latest AS (
    SELECT d.*, ROW_NUMBER() OVER (
        PARTITION BY d.question_id ORDER BY r.run_ts DESC) AS rn
    FROM dbo.defects AS d
    JOIN dbo.runs AS r ON r.run_id = d.run_id
), decided AS (
    SELECT a.*, ROW_NUMBER() OVER (
        PARTITION BY a.question_id ORDER BY a.approved_ts DESC) AS rn
    FROM dbo.approvals AS a
)
SELECT
    l.question_id                                   AS [Question],
    q.prompt                                        AS [Asked],
    l.classification                                AS [Problem],
    l.instruction_target                            AS [Target],
    l.proposed_instruction                          AS [Add this instruction],
    l.rationale                                     AS [Why],
    l.tier                                          AS [Tier],
    l.auto_appliable                                AS [Approvable],
    CASE
        WHEN d.decision IS NULL           THEN 'awaiting approval'
        WHEN d.decision = 'rejected'      THEN 'rejected'
        WHEN rm.approval_id IS NULL       THEN 'approved, not yet applied'
        WHEN rm.verified = 1              THEN 'applied and verified'
        ELSE 'applied, not yet verified'
    END                                             AS [Status],
    d.approved_by                                   AS [Approved by]
FROM latest AS l
JOIN dbo.questions AS q ON q.question_id = l.question_id
LEFT JOIN decided AS d ON d.question_id = l.question_id AND d.rn = 1
LEFT JOIN dbo.remediations AS rm
       ON rm.approval_id = d.approval_id AND rm.persisted = 1
WHERE l.rn = 1;
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'ix_answers_question' AND object_id = OBJECT_ID('dbo.answers'))
    CREATE INDEX ix_answers_question   ON dbo.answers(question_id);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'ix_defects_question' AND object_id = OBJECT_ID('dbo.defects'))
    CREATE INDEX ix_defects_question   ON dbo.defects(question_id);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'ix_approvals_question' AND object_id = OBJECT_ID('dbo.approvals'))
    CREATE INDEX ix_approvals_question ON dbo.approvals(question_id);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'ix_approvals_mirror' AND object_id = OBJECT_ID('dbo.approvals'))
    CREATE INDEX ix_approvals_mirror   ON dbo.approvals(mirrored_ts);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'ix_feedback_question' AND object_id = OBJECT_ID('dbo.feedback'))
    CREATE INDEX ix_feedback_question  ON dbo.feedback(question_id);
GO
